### ISSUE TITLE
How to run this code

### ISSUE THREAD

**Issue by diemtran1005** [rda-ela/SNN-Adversarial-Attacks#1]
I am interested in your paper and want to be set up your code. But I do not how to run it. Please take time to write a clear guidance. Thanks so much.  I am looking your forward.

**Comment by rda-ela** [comment]
Hi @diemtran1005, I've added the dependencies for the scripts. The [Norse](https://github.com/norse/norse) library is only needed if you are interested in running the SNN script. After installing the requirements, the scripts should run as any other python script. The SNN might look stuck when ran but after the training, applying the attack to the model takes a bit of time, even if you are using a GPU. I'm leaving the issue open until you give me a feedback.

**Comment by diemtran1005** [comment]
I can be running now. Thanks very much for your support.

**Comment by rda-ela** [comment]
Great!
